Lab 3 Multitasking: task_user Class Reference
task_user Class Reference
#include <task_user.h>
Public Member Functions
task_user (const char *, unsigned portBASE_TYPE, size_t, emstream *)
void run (void)
void print_status (emstream &)
Protected Member Functions
void print_help_message (void)
void show_status (void)
void motor_menu (void)
void motor_settings (void)
Protected Attributes
emstream * p_serial
uint32_t runs
Detailed Description
This task reads measurements that were taken by the data acquisition task in task_daq.* and puts those measurements into a queue.
Definition at line 57 of file task_user.h.
Constructor & Destructor Documentation
task_user::task_user (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
This constructor creates a new data acquisition task. Its main job is to call the parent class's constructor which does most of the work.
Parameters:
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.) which can be used by this task to communicate (default: NULL)
Definition at line 58 of file task_user.cpp.
References p_serial, and runs.
Member Function Documentation
void task_user::motor_menu (void) [protected]
This method prints out the diferent options for the motor menu imlpmented in run(). It shows the possible inputs it accepts as well as what they do.
Definition at line 244 of file task_user.cpp.
References p_serial.
Referenced by motor_settings(), and run().
void task_user::motor_settings (void) [protected]
This function is the implementation of the motor menu. Given correct inputs it will let you change motor, change pot state, change power settings, run the brakes, and switch back to the main menu. Incorrect input are more or less ignored
Definition at line 262 of file task_user.cpp.
References motor_menu(), p_serial, and pot_1.
Referenced by run().
void task_user::print_help_message (void) [protected]
This method prints out the diferent options for the main menu imlpmented in run(). It shows the possible inputs it accepts as well as what they do.
Definition at line 168 of file task_user.cpp.
References p_serial.
Referenced by run().
void task_user::print_status (emstream & ser_thing)
This method prints information about the status of this task. It is called by the overloaded "<<" operator so that when the task prints itself to a serial device, whatever this method wants printed gets printed.
Parameters:
ser_thing The serial device to which information will be printed
Definition at line 231 of file task_user.cpp.
References runs.
void task_user::run (void)
This run method is called by the RTOS and contains a loop in which the task checks for user input and characters in the print queue, dealing with each in the appropriate manner.
This task is the main loop that runs the menu. You can chose options from the main menu, including printing the time, version, and stack, or you can go to the motor menu implemented in motor_menu()
Definition at line 79 of file task_user.cpp.
References motor_menu(), motor_settings(), p_serial, print_help_message(), print_ser_queue, runs, and show_status().
void task_user::show_status (void) [protected]
This method displays information about the status of the system, including
The name and version of the program
The name, status, priority, and free stack space of each task
Processor cycles used by each task
Amount of heap space free and setting of RTOS tick timer
Definition at line 188 of file task_user.cpp.
References p_serial, and PROGRAM_VERSION.
Referenced by run().
Member Data Documentation
emstream* task_user::p_serial [protected]
This pointer allows all the methods in this task to use the serial port, or whatever serial device is being used to communicate with the user.
Definition at line 65 of file task_user.h.
Referenced by motor_menu(), motor_settings(), print_help_message(), run(), show_status(), and task_user().
uint32_t task_user::runs [protected]
This variable counts the number of runs through this task's loop.
Definition at line 76 of file task_user.h.
Referenced by print_status(), run(), and task_user().
The documentation for this class was generated from the following files:
task_user.h
task_user.cpp